Ref
acid-design-lab/LLM_classifier pull request #4
Opened 2024-02-11 16:17 UTC by essenceD

это последняя попытка

2024-02-13 17:06 UTC, dmitrav commented
Собственно, тут написано, что merge пока сделать невозможно из-за наличия конфликтов. Их надо разрешить.

2024-02-13 17:18 UTC, essenceD commented
изменения:
1) реализованы классы провайдеров. теперь проще добавлять новые сетки.
2) реализован класс датасета (думаю, что понадобится, если будем модифицировать данные)
3) структурированы вспомогательные функции.
4) добавлен режим dry_run для приблизительной оценки стоимости запроса.
5) добавлено логирование
6) изменен формат ответа модели с ТХТ на JSON
7) добавлены перехваты ошибок

2024-02-13 17:20 UTC, ruby-mle commented
> Собственно, тут написано, что merge пока сделать невозможно из-за наличия конфликтов. Их надо разрешить.

я попробую

2024-02-13 18:23 UTC, dmitrav requested changes
Прошелся по коду, оставил некоторые комментарии, которые относятся не только к конкретным файлам, но и вообще к оформлению кода и репозитория. Предлагаю еще немного времени потратить, чтобы завершить рефакторинг.

2024-02-13 18:23 UTC, dmitrav commented on classifier.log
Что это за файл и зачем он в этом репозитории?

2024-02-13 18:23 UTC, dmitrav commented on classifier/__main__.py
> +        elif config.provider == "mistral":
Все константы лучше убирать в отдельный файл и импортировать из него. Это позволяет избегать случайных опечаток и упрощает рефакторинг в случае замены констант.
Буквально все константы (численные / строковые / другие) лучше изолировать в отдельный файл `constants.py`.

2024-02-13 18:23 UTC, dmitrav commented on classifier/__main__.py
Я бы посоветовал обернуть весь этот код в функцию (или разбить на несколько), а затем вызвать одну функцию в основном блоке.

Например, весь твой код после импортов лежит в функции `cli()`.
Далее, ты пишешь:

    if __name__ == "__main__":
        cli()

2024-02-13 18:23 UTC, dmitrav commented on classifier/configuration.py
> +        data["seed"] = int(data.get("seed"))
Куча констант, которые надо бы изолировать.

2024-02-13 18:23 UTC, dmitrav commented on classifier/configuration.py
> +class Configuration(dict[str, str | int | bool | Path]):
А почему у класса нет инициализации?

Кстати, docstring я бы тоже добавил.

2024-02-13 18:23 UTC, dmitrav commented on classifier/dataset.py
> +    ) -> Dataset:
Было бы неплохо добавить docstring, чтобы пояснить хотя бы поверхностно, что здесь происходит.

2024-02-13 18:23 UTC, dmitrav commented on classifier/dataset.py
> +                data,
Вложенные лямбды — это плохо, потому что код становится очень сложно читать. Лучше разбить это на отдельные функции с понятными названиями и описаниями фукнционала.

2024-02-13 18:23 UTC, dmitrav commented on classifier/providers/mistral_provider.py
В этом файле особенно много констант, которые нужно изолировать.

2024-02-13 18:23 UTC, dmitrav commented on classifier/providers/openai_provider.py
Аналогично, очень много констант.

2024-02-13 18:23 UTC, dmitrav commented on classifier/utils.py
> +def create_result_directory(config: dict) -> Path:
Описание функции не помешало бы.

2024-02-13 18:23 UTC, dmitrav commented on config
Этот конфиг относится к конкретному проекту и к конкретному типу экспериментов внутри проекта. Я бы как-то отразил это в репозитории (выделил бы отдельную папку под проекты со своими конфигами или что-то типа того).

2024-04-02 11:21 UTC, dmitrav commented
@essenceD Что с этим PR? Он висит уже больше месяца.

2024-04-03 15:19 UTC, closed without merging